name: "example-action"
description: "An example of building github actions with Go"

inputs:
  create_tag:
    required: false
    description: "Whether this action will create a tag"
    default: "false"

  major_version: 
    required: true
    description: "The name of the branch calling the action"
    default: "1"

  token:
    required: false
    description: "The token to use for the push action"
    default: ${{ github.token}}

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.create_tag }}
    - ${{ inputs.major_version }}
